### ISSUE TITLE
Sending transactional emails do not work with gleam_httpc on OTP 24

### ISSUE THREAD

**Issue by jrstrunk** [aosasona/plunk.gleam#7]
The code below does not work, but will work if called with hackney instead of httpc.
```gleam
import gleam/option.{None}
import gleam/io
import gleam/httpc
import plunk
import plunk/transactional.{Address, TransactionalEmail}

pub fn main() {
  let instance =
    plunk.new(key: "sk-xxxx")

  let req =
    instance
    |> transactional.send(mail: TransactionalEmail(
      to: Address("hello@example.com"), 
      subject: "Test Email!",
      body: "Hello!",
      name: None,
      from: None,
    ))

  let assert Ok(res) = httpc.send(req)

  transactional.decode(res)
  |> io.debug
}
```

Not sure if this is known. I am not sure which is better in general, so I will just use Hackney for now. Thanks for the great work on this package! I did not know of Plunk before, but now I am excited to use their services.

**Comment by aosasona** [comment]
Hiya @jrstrunk!
That's strange, I am not sure what the issue might be yet but I will have a look when I have some free time and leave this issue open till then as a self-reminder.

Also, I edited your original comment to remove the secret key you accidentally included haha.

**Comment by jrstrunk** [comment]
Oh wow hahaha thanks for that

**Comment by aosasona** [comment]
Thank you for reporting that! I have only tested with Hackney and use Hackney myself.

**Comment by aosasona** [comment]
I just tested with httpc and it works for other requests but not for this, you are right, the Plunk API returns a `Bad Request` with "Required" as the message, and I have no idea what is required or what parameter httpc is dumping but I don't think it is a problem with this library since the same request works fine in Hackney and uses the built-in Gleam `Request` type. Although, the `httpc` has a warning related to how it handles HTTPS prior to OTP 26 but I also don't think that's the issue. I am unable to dig further right now but I will close this and leave it pinned.

**Recommendation for anyone looking at this issue**: use `hackney` instead, it seems to be more fully featured and is directly tested against.
